name: CI

# Define os gatilhos para o workflow
on:
  push:
    branches: [ master ]       
  pull_request:
    branches: [ master ]        

jobs:
  build:

    runs-on: ubuntu-latest     # Define o sistema operacional do runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Clona o repositório

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'   # Distribuição do JDK
        java-version: '17'        # Versão do Java

    - name: Check Java version
      run: java -version

    - name: Check Maven version
      run: mvn -version

    - name: List project files
      run: ls -R

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2               # Diretório do cache do Maven
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Chave do cache
        restore-keys: |
          ${{ runner.os }}-maven-  # Chaves de restauração

    - name: Build with Maven
      run: mvn clean install -X -DskipTests  # Compila o projeto com logs detalhados e sem executar os testes

    - name: Run tests
      run: mvn test                        # Executa os testes

    - name: Display Test Results
      run: |
        if [ -d "target/surefire-reports" ]; then
          echo "Test Results:"
          cat target/surefire-reports/*.txt
        else
          echo "No test reports found."
        fi
